version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  install:
    working_directory: ~/mern-starter
    # Reuse Docker container specification given by the node Orb
    executor: node/default
    steps:
      - checkout
      # Install the latest npm - the node Orb takes care of it
      - node/install-npm
      # Install dependencies - the node Orb take care of installation and dependency caching
      - node/install-packages:
          app-dir: ~/mern-starter
          cache-path: node_modules
          override-ci-command: npm i
      # Save workspace for subsequent jobs (i.e. test)
      - persist_to_workspace:
          root: .
          paths:
            - .
  style:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Style
          command: npm run lint
          env:
            CI: false
  build:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Style
          command: npm run build

workflows:
  test:
    jobs:
      - install
      - style:
          requires:
            - install
      - build:
          requires:
            - install
